// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// internal_find_orf
IntegerVector internal_find_orf(const std::string seq, const IntegerVector start, const std::vector< std::string > stop_codon);
RcppExport SEXP _TranScribeR_internal_find_orf(SEXP seqSEXP, SEXP startSEXP, SEXP stop_codonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type seq(seqSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type start(startSEXP);
    Rcpp::traits::input_parameter< const std::vector< std::string > >::type stop_codon(stop_codonSEXP);
    rcpp_result_gen = Rcpp::wrap(internal_find_orf(seq, start, stop_codon));
    return rcpp_result_gen;
END_RCPP
}
// cxx_find_orf
List cxx_find_orf(std::vector< std::string > seqs, List starts, const std::vector< std::string > stop_codon);
RcppExport SEXP _TranScribeR_cxx_find_orf(SEXP seqsSEXP, SEXP startsSEXP, SEXP stop_codonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector< std::string > >::type seqs(seqsSEXP);
    Rcpp::traits::input_parameter< List >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< const std::vector< std::string > >::type stop_codon(stop_codonSEXP);
    rcpp_result_gen = Rcpp::wrap(cxx_find_orf(seqs, starts, stop_codon));
    return rcpp_result_gen;
END_RCPP
}
// cxx_merge_ranges
IntegerVector cxx_merge_ranges(const IntegerVector chrom, const IntegerVector start, const IntegerVector end, const IntegerVector strand, const IntegerVector grp, const IntegerVector tol);
RcppExport SEXP _TranScribeR_cxx_merge_ranges(SEXP chromSEXP, SEXP startSEXP, SEXP endSEXP, SEXP strandSEXP, SEXP grpSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector >::type chrom(chromSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type start(startSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type end(endSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type strand(strandSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type grp(grpSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(cxx_merge_ranges(chrom, start, end, strand, grp, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TranScribeR_internal_find_orf", (DL_FUNC) &_TranScribeR_internal_find_orf, 3},
    {"_TranScribeR_cxx_find_orf", (DL_FUNC) &_TranScribeR_cxx_find_orf, 3},
    {"_TranScribeR_cxx_merge_ranges", (DL_FUNC) &_TranScribeR_cxx_merge_ranges, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_TranScribeR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
