# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

internal_find_orf <- function(seq, start, stop_codon) {
    .Call(`_TranScribeR_internal_find_orf`, seq, start, stop_codon)
}

cxx_find_orf <- function(seqs, starts, stop_codon) {
    .Call(`_TranScribeR_cxx_find_orf`, seqs, starts, stop_codon)
}

cxx_merge_ranges <- function(chrom, start, end, strand, grp, tol) {
    .Call(`_TranScribeR_cxx_merge_ranges`, chrom, start, end, strand, grp, tol)
}

